#!/bin/bash

export EDITOR=vim
# export BROWSER=chromium-browser

export PATH="$HOME/bin:$HOME/priv/dotfiles/scripts:$PATH"
export PATH=$PATH:~/.cabal/bin:$HOME/Library/Haskell/bin:~/.xmonad/bin


. ~/.shell/env
. ~/.shell/config
. ~/.shell/aliases
. ~/.shell/functions


BLUE="\[\033[0;34m\]"
LIGHT_GRAY="\[\033[0;37m\]"
LIGHT_GREEN="\[\033[1;32m\]"
LIGHT_BLUE="\[\033[1;34m\]"
LIGHT_CYAN="\[\033[1;36m\]"
YELLOW="\[\033[1;33m\]"
WHITE="\[\033[1;37m\]"
RED="\[\033[0;31m\]"
NO_COLOUR="\[\033[0m\]"

# PS1="$LIGHT_BLUE\w$NO_COLOUR \$(git_cwd_info)$LIGHT_GRAY■ $NO_COLOUR "

