#!/bin/bash

function is_monitor_on() {
    xset q | grep 'Monitor is On' >/dev/null
    return $?
}

function is_screensaver_active() {
    gnome-screensaver-command -q | grep 'The screensaver is active' >/dev/null
    return "$?"
}

function turn_monitor_off_after()
{
    TIMEOUT_s="$1"
    sleep "$TIMEOUT_s"
    is_screensaver_active || return 1
    is_monitor_on && xset dpms force off
    return 0
}


is_monitor_on && (
    gnome-screensaver-command -l &
    turn_monitor_off_after 60 &
)
